site_name: "MeshCentral Documentation"
nav:
  - Home: index.md

  - Install:
    - install/quickstart.md
    - install/install.md

  - MeshCentral:
      - 'MeshCentral Guide': 'meshcentral/index.md'
      - 'All Configuration Options': 'meshcentral/config.md'
      - 'Agent Information': 'meshcentral/agents.md'
      - 'Assistant': 'meshcentral/assistant.md'
      - 'Code Signing': 'meshcentral/codesigning.md'
      - 'Debugging': 'meshcentral/debugging.md'
      - 'Device Tabs': 'meshcentral/devicetabs.md'
      - 'Plugins': 'meshcentral/plugins.md'
      - 'SSL': 'meshcentral/SSLnletsencrypt.md'
      - 'Security': 'meshcentral/security.md'
      - 'Tokens': 'meshcentral/tokens.md'
      - 'FAQ': 'meshcentral/faq.md'
      - 'Tips n Tricks': 'meshcentral/tipsntricks.md'
      - 'Messaging': 'messaging/index.md'
      - 'Customization': 'meshcentral/customization.md'
      - 'openidConnectStrategy': 'meshcentral/openidConnectStrategy.md'
      
  - Design and Architecture:
    - design/index.md

  - MeshCmd:
    - meshcmd/index.md

  - MeshCtrl:
    - meshctrl/index.md

  - Mesh Router:
    - meshrouter/index.md

  - Intel AMT:
    - intelamt/index.md

  - How to Contribute:
    - how-to-contribute/index.md

  - Other:
    - other/adfs_sso_guide.md
    - other/meshcentral_satellite.md

site_description: "A remote monitoring and management tool"
site_author: "Ylianst and others"
site_url: "https://ylianst.github.io/MeshCentral/"

dev_addr: "0.0.0.0:8010"

# Repository
repo_name: "Ylianst/MeshCentral"
repo_url: "https://github.com/Ylianst/MeshCentral"
edit_uri: ""

theme:
  name: "material"
  logo: "images/favicon.ico"
  favicon: "images/favicon.ico"
  language: en
  locale: en
  include_sidebar: false
  palette:
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    #- navigation.expand
    - navigation.top
    - navigation.instant
    - search.suggest
extra_css:
  - stylesheets/extra-new.css
extra:
  generator: false
plugins:
  - search
  - print-site

markdown_extensions:
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.mark
  - pymdownx.smartsymbols
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
