name: Docker-Builder

on:
  push:
    branches:
      - master
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY_USERNAME: ${{ github.repository_owner || 'DaanSelen' }} # This is done so I can test the workflow with nektos/act

jobs:
  check-token:
    name: Check Token
    runs-on: ubuntu-latest
    outputs:
      token_defined: ${{ steps.token_check.outputs.token_defined }}
    steps:
      - name: Check token
        id: token_check
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        if: "${{ env.MY_TOKEN != '' }}"
        run: echo "token_defined=true" >> "$GITHUB_OUTPUT"

  build-complete-image:
    name: build-complete
    runs-on: ubuntu-latest
    needs: [check-token]
    if: needs.check-token.outputs.token_defined == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.MY_TOKEN }}

      - name: Install Translate Packages (allowed to fail)
        working-directory: ./translate
        run: node translate.js || true

      - name: Run extractall
        working-directory: ./translate
        run: node translate.js extractall

      - name: Run minifyall
        working-directory: ./translate
        run: node translate.js minifyall

      - name: Run translateall
        working-directory: ./translate
        run: node translate.js translateall

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            INCLUDE_MONGODB_TOOLS=true
            INCLUDE_POSTGRESQL_TOOLS=true
            INCLUDE_MARIADB_TOOLS=true
            DISABLE_MINIFY=yes
            DISABLE_TRANSLATE=yes
            PREINSTALL_LIBS=true
  
  build-mongodb-image:
    name: build-mongodb
    runs-on: ubuntu-latest
    needs: [check-token]
    if: needs.check-token.outputs.token_defined == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.MY_TOKEN }}

      - name: Install Translate Packages (allowed to fail)
        working-directory: ./translate
        run: node translate.js || true

      - name: Run extractall
        working-directory: ./translate
        run: node translate.js extractall

      - name: Run minifyall
        working-directory: ./translate
        run: node translate.js minifyall

      - name: Run translateall
        working-directory: ./translate
        run: node translate.js translateall

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}-mongodb
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            INCLUDE_MONGODB_TOOLS=true
            INCLUDE_POSTGRESQL_TOOLS=false
            INCLUDE_MARIADB_TOOLS=false
            DISABLE_MINIFY=yes
            DISABLE_TRANSLATE=yes
            PREINSTALL_LIBS=true

  build-postgresql-image:
    name: build-postgresql
    runs-on: ubuntu-latest
    needs: [check-token]
    if: needs.check-token.outputs.token_defined == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.MY_TOKEN }}

      - name: Install Translate Packages (allowed to fail)
        working-directory: ./translate
        run: node translate.js || true

      - name: Run extractall
        working-directory: ./translate
        run: node translate.js extractall

      - name: Run minifyall
        working-directory: ./translate
        run: node translate.js minifyall

      - name: Run translateall
        working-directory: ./translate
        run: node translate.js translateall

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}-postgresql
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            INCLUDE_MONGODB_TOOLS=false
            INCLUDE_POSTGRESQL_TOOLS=true
            INCLUDE_MARIADB_TOOLS=false
            DISABLE_MINIFY=yes
            DISABLE_TRANSLATE=yes
            PREINSTALL_LIBS=true
  
  build-mariadb-image:
    name: build-mariadb
    runs-on: ubuntu-latest
    needs: [check-token]
    if: needs.check-token.outputs.token_defined == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.MY_TOKEN }}

      - name: Install Translate Packages (allowed to fail)
        working-directory: ./translate
        run: node translate.js || true

      - name: Run extractall
        working-directory: ./translate
        run: node translate.js extractall

      - name: Run minifyall
        working-directory: ./translate
        run: node translate.js minifyall

      - name: Run translateall
        working-directory: ./translate
        run: node translate.js translateall

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}-mariadb
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            INCLUDE_MONGODB_TOOLS=true
            INCLUDE_POSTGRESQL_TOOLS=false
            INCLUDE_MARIADB_TOOLS=true
            DISABLE_MINIFY=yes
            DISABLE_TRANSLATE=yes
            PREINSTALL_LIBS=true